---
- name: Loading defined modules
  loop: "{{ modprobe_general + modprobe_extra }}"
  community.general.modprobe:
    name: "{{ omit if item.name is undefined else item.name }}"
    params: "{{ omit if item.params is undefined else item.params }}"
    state: "{{ 'present' if item.state is undefined else item.state }}"
  tags:
    - modprobe

- name: Write modules config
  ansible.builtin.template:
    src: config.j2
    dest: /etc/modules
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - modprobe

...
